### ISSUE TITLE
Could not find 'nx' module in this workspace.

### ISSUE THREAD

**Issue by wuarmin** [javierbrea/pnpm-nx-monorepo-example#10]
Hey @javierbrea,

thanks for this post https://www.javierbrea.com/blog/pnpm-nx-monorepo-02/. I build a mono-repo based on your guide. I have one app named `myapp` and two packages named `shared-ui` and `shared-features`.

To build `myapp` I have following nx-configuration:

```json
"targetDependencies": {
    "start": [
      {
        "target": "build",
        "projects": "dependencies"
      }
    ]
  }
``` 
I think nowadays, it could be changed to:
```json
  "targetDefaults": {
    "start": {
      "dependsOn": ["^build"]
    }
  }
```

Doesn't matter! Either way, I get the following error when I try to start myapp and use latest nx. The packages are built properly, but the `myapp` start fails.

f I call `pnpm nx start myapp`, I get following error:
```txt
dist/select-utils-14284a03.js              2.84 kB │ gzip: 1.06 kB
✓ built in 3.01s

> nx run myapp:start

Could not find 'nx' module in this workspace. Error: Invalid source or target versions. Source: 5.0, Target: 5.1.
Only backwards compatibility between "5.1" and "5.0" is supported.
This error can be caused by "@nrwl/..." packages getting out of sync or outdated project graph cache.
Check the versions running "nx report" and/or remove your "nxdeps.json" file (in node_modules/.cache/nx folder).
```

It seems the reason is, that `nx` is installed as a dep of the workspace, as you also prefer and therefore `nx run myapp:start` get called without `pnpm` prefixed. What do you think. Do you know, how I can fix this?

Thanks and best regards!

**Comment by javierbrea** [comment]
Hi @wuarmin , thank you, I'm glad you liked the post 😃 

I think that the error may be related to some kind of duplicated dependency, or installation problem. Have you tried to run the commands that error is suggesting to get more information? (`nx report`). Removing the `node_modules/.cache` folder does not work either?

To be honest, I have never received such error. So, if you could provide more details about your dependencies, NodeJs and Pnpm versions, operating system, etc, maybe I could try to reproduce it. If possible, preparing a public repository with the whole setup to reproduce the error would be great.

**Comment by wuarmin** [comment]
Hey @javierbrea,
thanks for the response. 

Here's the output of the `nx report`:

```txt
> repo@1.0.0 nx /home/node/repo
> nx "report"


 >  NX   Report complete - copy this into the issue template

   Node : 18.15.0
   OS   : linux x64
   pnpm : 8.1.0
   
   nx          : 15.9.2
   @nrwl/cli   : 15.9.2
   @nrwl/tao   : 15.9.2
   typescript  : 5.0.3
```
The weird thing is, it works now. The error went away. 

I'm developing in a docker-container and this is my Dockerfile:
```dockerfile
ARG NODE_VERSION
ARG DISTRO_NAME=bullseye

FROM node:$NODE_VERSION-$DISTRO_NAME-slim

# Create a user
USER node
ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
ENV PATH=$PATH:/home/node/.npm-global/bin

# Install pnpm globally
RUN npm install -g pnpm

# Create a directory for the repo code
RUN mkdir -p /home/node/repo
RUN chown -R node:node /home/node/repo

WORKDIR /home/node/repo
```
and the docker-compose.yml file:

```yml
version: '2.4'

x-app: &app
  build:
    context: .dockerdev
    dockerfile: Dockerfile
    args:
      NODE_VERSION: '18.15.0'
  environment: &env
    - NODE_ENV=development
    - HISTFILE=/home/node/repo/logs/.bash_history
  image: my-monorepo:latest
  tmpfs:
    - /tmp

services:
  runner:
    <<: *app
    stdin_open: true
    tty: true
    command: /bin/bash
    ports:
      - "3000:3000"
      - "5173:5173"
      - "4211:4211" # nx graph
    volumes:
      - .dockerdev/.bashrc:/root/.bashrc:ro
      - /app/node_modules
      - ./:/home/node/repo
```

Do you have any comments about this setting?

Thanks and best regards!

**Comment by javierbrea** [comment]
Hi again @wuarmin,

If the error disappeared then I suppose it was related to the nx cache or to an installation problem.
About your Docker configuration, maybe binding your whole local folder to the project folder inside the Docker container could produce some issues, because the dependencies installed in Docker could differ from the dependencies installed locally (in case you install them also in the host, for example). And it may also produce performance issues due to the huge number of files created by the NPM installation. One thing I usually do is creating a volume and assigning it to the `node_modules` folder in the Docker container, so it is not shared. For example:

```yaml
volumes:
  node_modules:
services:
  runner:
    volumes:
      - ./:/workspace # This binds the whole workspace
      - node_modules:/workspace/node_modules #This avoids to share the node_modules folder
```

Anyway, this is not related to the example in this repository, unless a Docker config example is also added (which, in the other hand, may be interesting 😃 ). So, I'll close the issue. Thanks for sharing!

**Comment by wuarmin** [comment]
Hi @javierbrea,
thanks for the input! I changed my config to:

```dockerfile
ARG NODE_VERSION
ARG DISTRO_NAME=bullseye

FROM node:$NODE_VERSION-$DISTRO_NAME-slim

# Create a user
USER node
ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
ENV PATH=$PATH:/home/node/.npm-global/bin

# Install pnpm globally
RUN npm install -g pnpm

# Create a directory for the repo code
# here I added the mkdir of the node_modules, in order to have the right permissions as a result
RUN mkdir -p /home/node/repo/node_modules
RUN chown -R node:node /home/node/repo

WORKDIR /home/node/repo
```
```yaml
version: '2.4'

x-app: &app
  build:
    context: .dockerdev
    dockerfile: Dockerfile
    args:
      NODE_VERSION: '18.15.0'
  environment: &env
    - NODE_ENV=development
    - HISTFILE=/home/node/repo/logs/.bash_history
  image: gru-bears:latest
  tmpfs:
    - /tmp

services:
  runner:
    <<: *app
    stdin_open: true
    tty: true
    command: /bin/bash
    ports:
      - "3000:3000"
      - "5173:5173"
      - "4211:4211" # nx graph
    volumes:
      - .dockerdev/.bashrc:/root/.bashrc:ro
      - node_modules:/home/node/repo/node_modules
      - ./:/home/node/repo

volumes:
  node_modules:
```
It works great :+1: , but when I run `pnpm install` I get the following warnings:
```txt
 WARN  EXDEV: cross-device link not permitted, link '/home/node/repo/.pnpm-store/v3/files/27/f6ae491d2e5c8ddaa960eb37288a0ffe10fa55714f79de8c17a3ebe6ae087920f35c17eb5621e1239495c8200cd9f1ba53f33075a4892efddf5a3c8e403b92' -> '/home/node/repo/node_modules/.pnpm/regenerator-runtime@0.13.11/node_modules/_tmp_340_7bf67a85af615d10b41475d47de619b2/LICENSE'
Falling back to copying packages from store
 WARN  EXDEV: cross-device link not permitted, link '/home/node/repo/.pnpm-store/v3/files/66/3ede53dcf7e0064de8fb8342a8f466cb79d4dd179cd0bf9b439355482cedcb276af12f6891cf2bcf9127470610878471dcef978ce02ee121057595bcb6ef0f' -> '/home/node/repo/node_modules/.pnpm/@testing-library+jest-dom@5.16.5/node_modules/@testing-library/_tmp_340_bc0400c95c8e19c6857511563c60b171/LICENSE'
Falling back to copying packages from store
 WARN  EXDEV: cross-device link not permitted, link '/home/node/repo/.pnpm-store/v3/files/1d/0688424f69c0e7322aeb720e4e28d9af3b5a7a2dc18b8b198156e377a61a6e05bc824528fca0f8e61ac39b137a028029ff82e5229ad400a3cc22e2bdb687ad-exec' -> '/home/node/repo/node_modules/.pnpm/@types+testing-library__jest-dom@5.14.5/node_modules/@types/_tmp_340_0bf67ca19b0685ee23938177a0b3002d/LICENSE'
Falling back to copying packages from store
 WARN  EXDEV: cross-device link not permitted, link '/home/node/repo/.pnpm-store/v3/files/1d/0688424f69c0e7322aeb720e4e28d9af3b5a7a2dc18b8b198156e377a61a6e05bc824528fca0f8e61ac39b137a028029ff82e5229ad400a3cc22e2bdb687ad-exec' -> '/home/node/repo/node_modules/.pnpm/@types+jest@29.5.0/node_modules/@types/_tmp_340_b5bf7fe67c6e97471844d710cbb8f2b7/LICENSE'
Falling back to copying packages from store
Falling back to copying packages from store
 WARN  2 other warnings
Falling back to copying packages from store
```
Do you know the reason?

Thanks!
